apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: server-list
spec:
  replicas: 1
  template:
    spec:
      repository: CommetDevTeam/commet_infra

